version: '3.2'
services:
  mysql: # Mysql container
    container_name: mysql
    image: mysql:5.7
    restart: always
    volumes:
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/logs:/var/log/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
      MYSQL_USER:     test
      MYSQL_PASSWORD: password
      TZ: Asia/Tokyo
    ports:
      - 3306:3306
  server:
    container_name: dojo-mission-server
    build:
      dockerfile: Dockerfile
      context: ./server
    ports:
      - 8080:8080
    environment:
       MYSQL_USER: root
       MYSQL_PASSWORD: password
       MYSQL_HOST: mysql
       MYSQL_PORT: 3306
       MYSQL_DATABASE: database
      
